### PR TITLE
adds certifi as a dependency and sets the pool to use it

### PR DESCRIPTION
**Pull request by daverck**
#6

### CODE REVIEW

**Comment by shazow** [comment]
Thanks!

**Comment by shazow** [comment]
Pretty sure urllib3 1.25 and newer do HTTPS verification by default. Shouldn't need to include certifi as a dependency.

If you'd like to confirm and make another PR, I'd really appreciate that.

**Comment by daverck** [comment]
Latest version of urllib3 is 1.24.1
With that version https verification don't work by default :
If I omit `cert_reqs='CERT_REQUIRED', ca_certs=certifi.where()` then my code show a warning.
if I remove certifi dependency it doesn't work either

I seems that next version would indeed do it by default :)
https://github.com/urllib3/urllib3/issues/1454
https://github.com/urllib3/urllib3/releases

**Comment by shazow** [comment]
Ah fair point, my bad! :)

**Comment by claudioclutter** [comment]
Thanks for this commit! Are you planning on doing a release (1.0.4?) with this change included?

**Comment by shazow** [comment]
@claudioclutter That's fair, I'll do that.

TBH this project is not actively maintained. I'm debating whether I should mark it Archived. But seems some people still rely on it?

**Comment by shazow** [comment]
Pushed v1.0.4

**Pull request merged**
